version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: kaban
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: test-cards

    env_file:
      - .env
      - ./frontend/.env
      
    ports:
      - "80:3200"
      - "8907:8907"
    


volumes:
  mongodb_data_container:
